const SOURCES = [
 {id:'resources',title:'Indiana FSSA — SNAP Food Assistance',url:'https://www.in.gov/fssa/dfr/snap-food-assistance/',keys:['resource','asset','bank','cash','car','vehicle','home','house'],text:'Indiana SNAP considers certain resources such as cash and money in bank accounts. Indiana identifies the home and transportation vehicles as excluded resources. A particular asset should be classified under the applicable rule rather than assumed countable.'},
 {id:'income',title:'Indiana FSSA — SNAP Income',url:'https://www.in.gov/fssa/dfr/snap-food-assistance/income/',keys:['income','gross','net','deduction','rent','mortgage','utility','medical','child support','dependent care','self-employment','business'],text:'Indiana publishes gross and net monthly SNAP income limits by household size and identifies allowable deductions that can include shelter costs, court-ordered child support, dependent care needed for work or training, certain self-employment expenses, and qualifying medical expenses for elderly or disabled household members. Exact treatment depends on the applicable rule and household facts.'},
 {id:'student',title:'Indiana FSSA Policy Manual — Student eligibility',url:'https://www.in.gov/fssa/dfr/files/ICES_Program_Policy_Manual.pdf',keys:['student','college','university','school','work-study'],text:'Indiana applies special SNAP eligibility rules to certain students enrolled at least half-time in higher education. Verified exceptions can include qualifying paid employment, work-study, TANF, specified caregiving circumstances, and qualifying employment or training programs.'},
 {id:'household',title:'Indiana FSSA Policy Manual — Household composition',url:'https://www.in.gov/fssa/dfr/files/ICES_Program_Policy_Manual.pdf',keys:['household','spouse','food','parent','child','under 22','roommate'],text:'SNAP household composition considers who purchases and prepares food together, but some relationships generally require people to be grouped together, including spouses living together and children under 22 living with a parent or stepparent.'},
 {id:'work',title:'Indiana FSSA — SNAP / Policy Manual work rules',url:'https://www.in.gov/fssa/dfr/snap-food-assistance/',keys:['work requirement','work rule','abawd','impact','employment','training'],text:'Indiana SNAP work-registration and time-limit rules have exemptions and compliance paths depending on facts such as age, disability, caregiving, pregnancy, responsibility for a child, work hours, and qualifying employment or training. Indiana implemented federal changes to these rules in 2025.'},
 {id:'immigration',title:'Indiana FSSA — SNAP / Policy Manual citizenship rules',url:'https://www.in.gov/fssa/dfr/snap-food-assistance/',keys:['citizen','citizenship','immigration','immigrant','noncitizen','alien'],text:'Citizenship and qualifying noncitizen status can affect SNAP eligibility. Noncitizen eligibility depends on specific legal classifications, and Indiana implemented federal changes in 2025. The tool must not infer a legal immigration category from nationality or free text.'},
 {id:'apply',title:'Indiana FSSA — SNAP Food Assistance',url:'https://www.in.gov/fssa/dfr/snap-food-assistance/',keys:['apply','application','portal','interview','document','verification','after i apply'],text:'Indiana residents can apply through the FSSA Benefits Portal. FSSA may conduct an interview and request verification of household circumstances, income, resources, and relevant expenses. FSSA makes the official eligibility determination.'}
];
function retrieve(q){const s=q.toLowerCase();return SOURCES.map(x=>({x,score:x.keys.reduce((n,k)=>n+(s.includes(k)?k.length:0),0)})).filter(v=>v.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(v=>v.x)}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
export async function onRequestPost(context){
 try{
  const body=await context.request.json(); const question=String(body.question||'').trim().slice(0,2000); if(!question)return json({error:'Question required'},400);
  const docs=retrieve(question); const screening=body.screening||null; const resultQuestion=/why|my result|my screening|agency review|screening result/i.test(question);
  if(!docs.length && !(screening&&resultQuestion)) return json({answer:'I cannot answer that reliably from the approved Indiana SNAP material currently loaded into this prototype. I will not guess. Please consult Indiana FSSA or add the relevant verified policy passage to the knowledge base.',sources:[],grounded:false});
  if(!context.env.OPENAI_API_KEY) return json({answer:'The approved-source retrieval succeeded, but the live AI service is not configured. Add the OPENAI_API_KEY secret to enable grounded natural-language answers.',sources:docs.map(({title,url})=>({title,url})),grounded:true,ai:false},503);
  const evidence=docs.map((d,i)=>`SOURCE ${i+1}: ${d.title}\n${d.text}\nURL: ${d.url}`).join('\n\n');
  const trace=(screening&&resultQuestion)?`\nSCREENING TRACE (deterministic; explain but do not alter):\n${JSON.stringify(screening)}`:'';
  const instructions=`You are the Indiana SNAP Navigator grounded benefits assistant. Answer ONLY from the APPROVED EVIDENCE and, when supplied, the deterministic SCREENING TRACE. Do not use model memory to add SNAP rules, thresholds, exceptions, dates, or legal conclusions. Do not make an official eligibility determination. If the evidence is insufficient, say exactly that and recommend Indiana FSSA review. Explain in plain language. Do not claim a source says something not present in the evidence. Keep the answer concise and useful.`;
  const api=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${context.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:context.env.OPENAI_MODEL||'gpt-5.6-luna',store:false,instructions,input:`USER QUESTION:\n${question}\n\nAPPROVED EVIDENCE:\n${evidence}${trace}`})});
  if(!api.ok){const t=await api.text();return json({error:'AI service error',detail:t.slice(0,300)},502)}
  const data=await api.json(); let answer=data.output_text;
  if(!answer && Array.isArray(data.output)) for(const item of data.output) if(Array.isArray(item.content)) for(const c of item.content) if(c.type==='output_text'&&c.text) answer=(answer||'')+c.text;
  return json({answer:answer||'No answer returned.',sources:docs.map(({title,url})=>({title,url})),grounded:true,ai:true});
 }catch(e){return json({error:'Request failed'},500)}
}

